### ISSUE TITLE
slang.txt missing

### ISSUE THREAD

**Issue by Jeff-Winchell** [04mayukh/YoungSheldon-at-SemEval-2021-Task-7-HaHackathon#2]
It is referenced in the task 1b notebook but the file is not in this repository

**Comment by Jeff-Winchell** [comment]
I commented out code so that only a blank list of slang term was used. The code ran (with a .57 RMSE). Though I wonder how it would have scored if I had the slang.txt file.

**Comment by 04mayukh** [comment]
I will add the slang.txt file today. You can go ahead with testing with that then.

**Comment by Jeff-Winchell** [comment]
Any update on when the slang.txt file will be added to this repository?

**Comment by 04mayukh** [comment]
I have added the slang.txt file. You can use it to analyse the effect on performance.
